In [1]:
import pandas as pd
import os
from tqdm import tqdm

import sys
sys.path.append('../')

from jem.model import jem
from jem.analyse import analyse
from jem.utils import *

/Users/amanmajid/opt/anaconda3/envs/jem_model/lib/python3.7/site-packages/geopandas/_compat.py:58: UserWarning: The installed version of PyGEOS is too old (0.6 installed, 0.8 required), and thus GeoPandas will not use PyGEOS.
  UserWarning,

In [2]:
# #--------------------------------------------
# # Get damaged nodes

# node_path = '../data/risk-results/direct_damages/electricity_network_v1.0_nodes/'

# collected = []
# for f in tqdm(os.listdir(node_path)):
#     if 'csv' in f:
#         data = pd.read_csv(node_path + f)
#         collected.append(data)
        

# collected = pd.concat(collected,ignore_index=True)
# nodes_damaged = collected.id.unique()

In [3]:
nodes = gpd.read_file('../data/spatial/infrasim-network/nodes.shp')
nodes_to_attack = nodes.loc[nodes.asset_type == 'junction'].head(5).id.to_list()

In [5]:
#--------------------------------------------
# Simulate damages in loop

# define input files
path_to_flows = '../data/csv/generated_nodal_flows.csv'
path_to_nodes = '../data/spatial/infrasim-network/nodes.shp'
path_to_edges = '../data/spatial/infrasim-network/edges.shp'

n = []
x = []
y = []

nodes_to_attack = ['node_23715']

count = 0
for i in tqdm(range(0,len(nodes_to_attack))):
    if count < 99999999999999:
        # print(count)
        # init model
        run = jem(path_to_nodes,
                path_to_edges,
                path_to_flows,
                #timesteps=1,
                print_to_console=False,
                nodes_to_attack=list(nodes_to_attack[i]),
                #edges_to_attack=['edge_25297'],
                super_source=True,
                super_sink=False)
        
        # build model
        run.build()
        
        # run model
        run.optimise(print_to_console=False)
        
        # init results
        results = analyse(model_run=run)
        
        # get results
        try:
            n.append(nodes_damaged[0:i][-1])
        except:
            pass
        x.append(count)
        y.append(results.customers_affected_total())

    count = count + 1

r = pd.DataFrame({'x' : x, 'y' : y})

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.72s/it]

In [6]:
results.nodes_with_shortfall()

Empty DataFrame
Columns: [node, shortfall, timestep]
Index: []

In [7]:
results.edge_flows[results.edge_flows.to_id=='node_23716']

             from_id       to_id  timestep  flow
7340      node_23715  node_23716         1   0.0
127034  super_source  node_23716         1   0.0

In [10]:
flows = pd.read_csv('../data/csv/generated_nodal_flows.csv')
flows

,timestep,node_1,node_67,node_80,node_84,node_85,node_87,node_89,node_91,node_95,...,node_42949,node_42950,node_42951,node_42952,node_42954,node_42956,node_42958,node_42959,node_42966,node_42967
0,1,20000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
def process_raw_consumption_data(path):
    '''Process raw consumption data from JPS
    '''
    elec_data  = pd.read_csv(path)
    elec_data  = elec_data[['PARISH','Year','PARISH LOAD']]
    # pivot data
    elec_data  = elec_data.pivot(index='PARISH',columns='Year')
    elec_data.columns = [str(i[1]) for i in elec_data.columns.values]
    elec_data = elec_data.reset_index()
    # convert str to data
    try:
        for col in ['2014', '2015', '2016', '2017', '2018', '2019', '2020',]:
            elec_data[col] = elec_data[col].str.strip().str.replace(',','')
            elec_data[col] = elec_data[col].astype(float)
    except:
        pass
    # rename parish col
    elec_data['Parish'] = elec_data['PARISH']
    elec_data = elec_data.drop(['PARISH'],axis=1)
    # rename parish names
    elec_data.Parish = elec_data.Parish.str.replace('Portmore', 'St. Catherine')
    elec_data.Parish = elec_data.Parish.str.replace('KSAN', 'St. Andrew')
    elec_data.Parish = elec_data.Parish.str.replace('KSAS', 'Kingston')
    # group KSAN and KSAS data
    elec_data = elec_data.groupby(by=['Parish']).sum().reset_index()
    # get latest year
    elec_data = elec_data[['Parish',max(elec_data.columns.drop('Parish'))]]
    return elec_data


def append_energy_data_to_boundaries(boundaries,elec_data):
    '''Combine energy data and admin boundaries
    '''
    elec_dict = elec_data.set_index('Parish')['2020'].to_dict()
    boundaries['consumption'] = boundaries['PARISH'].map(elec_dict)
    boundaries['ei'] = boundaries.consumption / boundaries.population
    boundaries['ei_uom'] = 'KW/person'
    return boundaries[['PARISH','population','consumption','ei','ei_uom',]]


def get_ei_by_parish():
    '''Get a dataframe of electricity intensities by parish
    '''
    elec_data = process_raw_consumption_data('../data/energy-demand/energy_consumption.csv')
    boundaries = gpd.read_file('../data/incoming_data/admin_boundaries.gpkg',layer='admin1')
    boundaries = append_energy_data_to_boundaries(boundaries,elec_data)
    return boundaries

In [43]:
elec_data = process_raw_consumption_data('../data/energy-demand/energy_consumption.csv')
elec_data

           Parish          2020
0       Clarendon  20552.796800
1         Hanover   7090.513699
2        Kingston  68633.481740
3      Manchester  14423.127850
4        Portland   5977.488584
5      St. Andrew  60978.961190
6         St. Ann  21057.214610
7   St. Catherine  54172.214620
8   St. Elizabeth  14726.015980
9       St. James  39988.904110
10       St. Mary   9180.799087
11     St. Thomas   6022.305936
12       Trelawny   7999.315068
13   Westmoreland  16439.029680

In [44]:
boundaries = gpd.read_file('../data/incoming_data/admin_boundaries.gpkg',layer='admin1')
boundaries

,PARISH,CODE,POP2001,POP1991,POIS_1996,X,Y,Shape_Length,Shape_Area,geometry
0,Clarendon,13013,236150.0,214704.0,32.0,217494.91000,145753.26000,233702.537232,1.192930e+09,"MULTIPOLYGON (((714915.204 630431.612, 714902...."
1,Hanover,9009,66825.0,66109.0,21.0,130750.76500,192777.79500,153711.318685,4.508339e+08,"MULTIPOLYGON (((611408.687 690675.451, 611433...."
2,Kingston,2001,95810.0,58474.0,31.0,274204.68657,146322.19382,75709.764578,2.271090e+07,"MULTIPOLYGON (((775874.795 648004.230, 775972...."
3,Manchester,12012,185267.0,159606.0,21.0,197664.04500,155069.19500,130212.743611,8.278671e+08,"MULTIPOLYGON (((702485.634 664881.284, 702808...."
4,Portland,4004,80025.0,76318.0,54.0,302241.99000,163895.58500,177592.475738,8.139675e+08,"MULTIPOLYGON (((781783.977 679496.535, 781811...."
5,St. Andrew,2002,554241.0,149427.0,31.0,276040.56500,156255.64000,132595.948600,4.338883e+08,"MULTIPOLYGON (((778963.120 646880.614, 778579...."
6,St. Ann,6006,166147.0,149427.0,36.0,224290.35000,186648.31500,175972.467550,1.210299e+09,"MULTIPOLYGON (((744614.858 690267.549, 744741...."
7,St. Catherine,14014,480657.0,381967.0,10.0,247265.42000,155284.10000,220343.438781,1.190630e+09,"MULTIPOLYGON (((730350.271 662355.621, 730364...."
8,St. Elizabeth,11011,145923.0,145652.0,23.0,169467.97000,155584.21000,151630.281911,1.210725e+09,"MULTIPOLYGON (((687425.898 651755.493, 687488...."
9,St. James,8008,174631.0,154194.0,21.0,158440.72000,190826.54500,138533.685936,5.911833e+08,"MULTIPOLYGON (((646193.180 696707.646, 646181...."
10,St. Mary,5005,111093.0,108780.0,27.0,261952.83500,180744.44000,155958.744438,6.112730e+08,"MULTIPOLYGON (((761770.010 694118.634, 761752...."
11,St. Thomas,3003,91297.0,84702.0,60.0,310770.25000,146587.45424,171187.493611,7.421790e+08,"MULTIPOLYGON (((804731.480 654331.186, 804776...."
12,Trelawny,7007,72816.0,712040.0,26.0,185741.24500,189424.49000,141086.116342,8.743146e+08,"MULTIPOLYGON (((672391.035 706733.917, 672423...."
13,Westmoreland,10010,138452.0,128366.0,44.0,146376.12270,173358.90500,166478.879941,7.852037e+08,"MULTIPOLYGON (((657455.955 676659.673, 657472...."

In [59]:
boundaries = gpd.read_file('../data/population-russell/population.gpkg')
boundaries.PARISH = boundaries.PARISH.str.title()
boundaries.loc[boundaries.PARISH.str.contains('Catherine'),'PARISH'] = 'St. Catherine'
boundaries.loc[boundaries.PARISH.str.contains('Mary'),'PARISH'] = 'St. Mary'
boundaries.loc[boundaries.PARISH.str.contains('Andrew'),'PARISH'] = 'St. Andrew'
boundaries.loc[boundaries.PARISH.str.contains('Elizabeth'),'PARISH'] = 'St. Elizabeth'
boundaries.loc[boundaries.PARISH.str.contains('Thomas'),'PARISH'] = 'St. Thomas'
boundaries.loc[boundaries.PARISH.str.contains('James'),'PARISH'] = 'St. James'
boundaries.loc[boundaries.PARISH.str.contains('Ann'),'PARISH'] = 'St. Ann'
boundaries = boundaries.groupby(by='PARISH').sum().reset_index()
boundaries

           PARISH         ED_ID          AREA     PERIMETER  population
0       Clarendon  6.831469e+08  1.196842e+09  3.644845e+06    245122.0
1         Hanover  1.523744e+08  4.502645e+08  1.328517e+06     69695.0
2        Kingston  2.364629e+07  2.212693e+07  2.895360e+05     88250.0
3      Manchester  4.473887e+08  8.352180e+08  2.552417e+06    189916.0
4        Portland  8.069354e+07  8.155198e+08  1.748260e+06     81815.0
5      St. Andrew  2.130833e+08  4.324212e+08  2.633387e+06    573264.0
6         St. Ann  2.175215e+08  1.205126e+09  2.985122e+06    172435.0
7   St. Catherine  1.482287e+09  1.193338e+09  4.132326e+06    516224.0
8   St. Elizabeth  3.649140e+08  1.204109e+09  3.019723e+06    150328.0
9       St. James  3.340596e+08  5.920711e+08  1.949781e+06    183900.0
10       St. Mary  1.496230e+08  6.127864e+08  2.132417e+06    113739.0
11     St. Thomas  7.268167e+07  7.422981e+08  1.888541e+06     94031.0
12       Trelawny  1.360780e+08  8.712748e+08  1.705614e+06     75240.0
13   Westmoreland  3.527384e+08  7.899589e+08  2.370016e+06    144133.0

In [60]:
append_energy_data_to_boundaries(boundaries,elec_data)

           PARISH  population   consumption        ei     ei_uom
0       Clarendon    245122.0  20552.796800  0.083847  KW/person
1         Hanover     69695.0   7090.513699  0.101736  KW/person
2        Kingston     88250.0  68633.481740  0.777717  KW/person
3      Manchester    189916.0  14423.127850  0.075945  KW/person
4        Portland     81815.0   5977.488584  0.073061  KW/person
5      St. Andrew    573264.0  60978.961190  0.106372  KW/person
6         St. Ann    172435.0  21057.214610  0.122117  KW/person
7   St. Catherine    516224.0  54172.214620  0.104939  KW/person
8   St. Elizabeth    150328.0  14726.015980  0.097959  KW/person
9       St. James    183900.0  39988.904110  0.217449  KW/person
10       St. Mary    113739.0   9180.799087  0.080718  KW/person
11     St. Thomas     94031.0   6022.305936  0.064046  KW/person
12       Trelawny     75240.0   7999.315068  0.106317  KW/person
13   Westmoreland    144133.0  16439.029680  0.114055  KW/person

In [51]:
6600/8760

0.7534246575342466