In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
from scipy.spatial import Voronoi
from shapely.geometry import Polygon

import sys
sys.path.append('../jamaica-infrastructure')

from scripts.preprocess.preprocess_utils import \
assign_node_weights_by_population_proximity,voronoi_finite_polygons_2d,extract_nodes_within_gdf

/Users/amanmajid/opt/anaconda3/envs/jem_model/lib/python3.7/site-packages/geopandas/_compat.py:58: UserWarning: The installed version of PyGEOS is too old (0.6 installed, 0.8 required), and thus GeoPandas will not use PyGEOS.
  UserWarning,

In [2]:
nodes = gpd.read_file('../data/spatial/infrasim-network/nodes.shp')
sinks = nodes[nodes['asset_type']=='sink'].reset_index(drop=True)
sinks = sinks#.head(500)
sinks.head(2)

admin_boundaries = gpd.read_file('../data/spatial/else/admin-boundaries.shp')
admin_boundaries.head(2)

# rename
sinks['parish'] = sinks['parish'].str.replace('Kingston','KSA')
sinks['parish'] = sinks['parish'].str.replace('St. Andrew','KSA')
admin_boundaries['Parish'] = admin_boundaries['Parish'].str.replace('KSA','KSA')
admin_boundaries['Parish'] = admin_boundaries['Parish'].str.replace('St','St.')

/Users/amanmajid/opt/anaconda3/envs/jem_model/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  # This is added back by InteractiveShellApp.init_path()

In [3]:
sinks.parish.unique()

array(['Clarendon', 'Hanover', 'KSA', 'Manchester', 'St. Ann',
       'St. Catherine', 'St. Elizabeth', 'St. James', 'St. Mary',
       'St. Thomas', 'Trelawny', 'Westmoreland', 'Portland'], dtype=object)

In [4]:
admin_boundaries.Parish.unique()

array(['KSA', 'Westmoreland', 'St. Ann', 'St. James', 'Clarendon',
       'Hanover', 'Manchester', 'Portland', 'St. Catherine', None,
       'St. Elizabeth', 'St. Mary', 'St. Thomas', 'Trelawny'],
      dtype=object)

In [5]:
node_id_column='id'
pop_id='population'
epsg=3448,
voronoi_path='../data/spatial/electricity_voronoi.shp',

combined_voronoi = []
combined_nodes = []

for unique_parish in sinks.parish.unique():
    
    nodes_dataframe = sinks.loc[sinks.parish.isin([unique_parish])].reset_index(drop=True).copy()
    #population_dataframe = pop_bound.loc[pop_bound.PARISH.isin([unique_parish])].reset_index(drop=True).copy()
    parish_dataframe = admin_boundaries.loc[admin_boundaries.Parish.isin([unique_parish])].reset_index(drop=True).copy()
    
    # load provinces and get geometry of the right population_dataframe
    sindex_parish_dataframe = parish_dataframe.sindex

    # create Voronoi polygons for the nodes
    xy_list = []
    for iter_, values in nodes_dataframe.iterrows():
        xy = list(values.geometry.coords)
        xy_list += [list(xy[0])]

    vor = Voronoi(np.array(xy_list))
    regions, vertices = voronoi_finite_polygons_2d(vor)
    min_x = vor.min_bound[0] - 0.1
    max_x = vor.max_bound[0] + 0.1
    min_y = vor.min_bound[1] - 0.1
    max_y = vor.max_bound[1] + 0.1

    mins = np.tile((min_x, min_y), (vertices.shape[0], 1))
    bounded_vertices = np.max((vertices, mins), axis=0)
    maxs = np.tile((max_x, max_y), (vertices.shape[0], 1))
    bounded_vertices = np.min((bounded_vertices, maxs), axis=0)

    box = Polygon([[min_x, min_y], [min_x, max_y], [max_x, max_y], [max_x, min_y]])

    poly_list = []
    for region in regions:
        polygon = vertices[region]
        # Clipping polygon
        poly = Polygon(polygon)
        poly = poly.intersection(box)
        poly_list.append(poly)

    poly_index = list(np.arange(0, len(poly_list), 1))

    poly_df = pd.DataFrame(list(zip(poly_index, poly_list)),
                                   columns=['gid', 'geometry'])

    gdf_voronoi = gpd.GeoDataFrame(poly_df, geometry = 'geometry') #,crs=f'epsg:{epsg}'
    
    # add nodes
    gdf_voronoi[node_id_column] = gdf_voronoi.progress_apply(    
            lambda row: extract_nodes_within_gdf(row['geometry'],nodes_dataframe,node_id_column),axis=1)
    
    # add parish
    gdf_voronoi['Parish'] = gdf_voronoi[node_id_column].map(nodes_dataframe.set_index('id')['parish'].to_dict())
    
    # rename geom cols
    gdf_voronoi['voronoi_geom'] = gdf_voronoi['geometry']
    parish_dataframe['parish_geom'] = parish_dataframe['geometry']
    
    # dissolve
    gdf_voronoi = pd.merge(gdf_voronoi,parish_dataframe[['Parish','parish_geom']],
                           how='left',on='Parish')
    
    # dropna/empty
    gdf_voronoi = gdf_voronoi[~gdf_voronoi.parish_geom.isna()].reset_index(drop=True)
    
#     for i,row in gdf_voronoi.iterrows():
#         try:
#             (row.voronoi_geom.buffer(0)).intersection(row.parish_geom.buffer(0))
#         except:
#             print('Problem at index: ' + str(i))
#             print('--> Voronoi geom: ' + str(row.voronoi_geom))
#             print('--> Parish geom: ' + str(row.parish_geom))
    
    try:
        gdf_voronoi['geometry'] = gdf_voronoi.progress_apply(lambda row: \
                    (row.voronoi_geom.buffer(0)).intersection(row.parish_geom.buffer(0)),axis=1)
    except:
       print('FAILED: ' + unique_parish)
    
    combined_voronoi.append(gdf_voronoi)
    combined_nodes.append(nodes_dataframe)
    
voronois = gpd.GeoDataFrame( pd.concat( combined_voronoi, ignore_index=True) )
voronois = voronois[['id','Parish','geometry']]
voronois = voronois[~voronois.geometry.is_empty].reset_index(drop=True)
voronois.to_file(driver='ESRI Shapefile',filename='../_tmp/voronoi-clipped.shp')

nodes = gpd.GeoDataFrame( pd.concat( combined_nodes, ignore_index=True) ) 
nodes.to_file(driver='ESRI Shapefile',filename='../_tmp/voronoi-nodes.shp')

print('Done!')

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1215/1215 [00:03<00:00, 319.87it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103275/103275 [04:26<00:00, 387.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 390/390 [00:00<00:00, 773.47it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13650/13650 [00:03<00:00, 4194.56it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2896/2896 [00:19<00:00, 150.41it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 379245/379245 [01:31<00:00, 4145.23it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 998/998 [00:02<00:00, 387.47it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73852/73852 [00:14<00:00, 5088.26it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1135/1135 [00:03<00:00, 313.46it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62425/62425 [00:18<00:00, 3370.55it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2550/2550 [00:15<00:00, 161.06it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 130050/130050 [00:42<00:00, 3057.69it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 858/858 [00:02<00:00, 387.83it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52338/52338 [00:14<00:00, 3715.10it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1063/1063 [00:03<00:00, 342.63it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80788/80788 [00:18<00:00, 4365.44it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 645/645 [00:01<00:00, 531.18it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29025/29025 [00:06<00:00, 4238.80it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 424/424 [00:00<00:00, 729.31it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23744/23744 [00:05<00:00, 4260.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 425/425 [00:00<00:00, 667.93it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16150/16150 [00:04<00:00, 3779.41it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 616/616 [00:01<00:00, 479.43it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47432/47432 [00:09<00:00, 5125.50it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 333/333 [00:00<00:00, 803.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14319/14319 [00:35<00:00, 405.31it/s]

Done!

In [7]:
voronois

,id,Parish,geometry
0,node_12,Clarendon,"POLYGON ((723180.240 638507.091, 722987.971 63..."
1,node_20,Clarendon,"MULTIPOLYGON (((702581.134 669903.077, 702577...."
2,node_20,Clarendon,"POLYGON ((702577.748 669883.113, 702432.556 66..."
3,node_24,Clarendon,"POLYGON ((704117.262 670569.533, 704125.523 67..."
4,node_24,Clarendon,"POLYGON ((703233.527 670618.427, 703751.389 67..."
...,...,...,...
22450,node_44233,Portland,"POLYGON ((800205.755 669381.152, 800528.085 66..."
22451,node_44233,Portland,"POLYGON ((799420.584 668334.221, 798789.515 66..."
22452,node_44233,Portland,"POLYGON ((800388.450 668505.878, 799420.584 66..."
22453,node_44236,Portland,"POLYGON ((790488.219 675355.664, 790491.455 67..."
22454,node_44238,Portland,"POLYGON ((805294.419 670795.237, 805114.522 67..."

In [10]:
nodes.set_index('id')['population'].to_dict()

{'node_12': 86.16717442828548,
 'node_20': 470.3442037705589,
 'node_24': 60.00596000902023,
 'node_25': 180.35874950827346,
 'node_27': 370.9404175408904,
 'node_29': 854.5035126091772,
 'node_31': 462.61178580339566,
 'node_35': 374.6352066306928,
 'node_37': 214.42500779872697,
 'node_39': 96.56173988086832,
 'node_43': 146.99023142817848,
 'node_44': 244.25614791154655,
 'node_49': 328.789018470177,
 'node_53': 342.636003583416,
 'node_55': 269.23579100897916,
 'node_57': 546.7348719670574,
 'node_61': 178.6444856245373,
 'node_62': 675.2067167444548,
 'node_64': 221.54390936779438,
 'node_65': 522.9539406355373,
 'node_67': 721.9594218517649,
 'node_68': 794.6024841533489,
 'node_70': 382.67880432790224,
 'node_71': 287.26073779918767,
 'node_73': 748.5186016773574,
 'node_75': 253.5570990456818,
 'node_88': 341.40423065583525,
 'node_92': 157.35425389255954,
 'node_93': 256.5390423479033,
 'node_94': 92.76297263107361,
 'node_104': 584.0170192707578,
 'node_107': 136.53216705640745,
 'node_110': 74.96426339992696,
 'node_112': 106.1362334850158,
 'node_115': 172.09171689339598,
 'node_118': 128.28324777877305,
 'node_119': 143.70602191363255,
 'node_120': 265.8380259115366,
 'node_122': 251.48996252885775,
 'node_126': 236.8087927101006,
 'node_130': 258.0984687922661,
 'node_133': 187.02096901522702,
 'node_138': 238.04364913342653,
 'node_140': 666.9056582912294,
 'node_149': 223.41949797336952,
 'node_150': 160.20893914498623,
 'node_169': 125.72488177327315,
 'node_170': 410.2762940329018,
 'node_173': 82.94407698933722,
 'node_176': 22.691457500032023,
 'node_177': 37.243696487065904,
 'node_179': 347.2591091555088,
 'node_181': 646.9635785893846,
 'node_183': 291.9381034634527,
 'node_185': 109.8317189449712,
 'node_187': 206.88065612995462,
 'node_189': 466.8082052059055,
 'node_192': 460.02938823564807,
 'node_194': 107.67062318645031,
 'node_199': 31.318706927624877,
 'node_203': 138.70260964126896,
 'node_205': 117.93910919589908,
 'node_206': 129.32230844026176,
 'node_208': 113.6219710810777,
 'node_209': 68.80661046642128,
 'node_213': 195.83267110893536,
 'node_219': 215.19734374486058,
 'node_221': 563.9707118620182,
 'node_228': 98.26214773955057,
 'node_230': 185.59880648073965,
 'node_232': 308.24146568512106,
 'node_234': 71.60986438434534,
 'node_242': 614.5375595580136,
 'node_250': 73.26162151654471,
 'node_252': 46.62132390189099,
 'node_253': 330.6945315382899,
 'node_263': 197.1971036148975,
 'node_265': 322.77592506365625,
 'node_268': 246.60921916402287,
 'node_271': 54.65698665260642,
 'node_272': 116.66376117665381,
 'node_275': 76.43906796715626,
 'node_277': 117.09210631282261,
 'node_291': 56.19257573524595,
 'node_300': 348.5617086899801,
 'node_305': 34.60707797274493,
 'node_308': 79.01661045680638,
 'node_310': 77.97577861528657,
 'node_313': 497.5079532840975,
 'node_316': 82.40681261969702,
 'node_318': 144.41355187138055,
 'node_319': 73.89105038230294,
 'node_326': 156.48274985008672,
 'node_330': 60.87994961462858,
 'node_333': 391.2687726629637,
 'node_338': 174.89457721972212,
 'node_342': 185.97371496587715,
 'node_349': 369.1070052047806,
 'node_356': 61.12664182250955,
 'node_357': 96.62959013426028,
 'node_359': 53.133076869768054,
 'node_362': 113.26438307688096,
 'node_367': 228.2149055704023,
 'node_369': 236.38359719500284,
 'node_371': 45.72240852849843,
 'node_372': 173.58622193714254,
 'node_373': 29.82234292317233,
 'node_374': 120.59559165383632,
 'node_376': 209.0075256679935,
 'node_377': 67.37531625256534,
 'node_378': 139.42333589702426,
 'node_381': 180.25738915127704,
 'node_384': 1001.8813658974807,
 'node_385': 498.2804096998438,
 'node_387': 168.59557810905042,
 'node_389': 112.88209034641098,
 'node_390': 71.13900486544313,
 'node_393': 21.946911105017058,
 'node_395': 250.91295483886262,
 'node_396': 80.95766130700468,
 'node_398': 53.42307728034468,
 'node_400': 90.16920065276668,
 'node_402': 118.85346130186626,
 'node_405': 77.00465059627129,
 'node_412': 76.72997126756235,
 'node_413': 216.409131257052,
 'node_414': 197.64888589676113,
 'node_416': 56.063752820117124,
 'node_418': 84.19148701736307,
 'node_423': 362.9097245140267,
 'node_425': 19.120290658804336,
 'node_429': 10.315840698964056,
 'node_431': 13.216256493942922,
 'node_433': 4.051931262180992,
 'node_435': 37.281983965741986,
 'node_437': 25.362371975918233,
 'node_438': 47.07016733380912,
 'node_440': 13.929645810129353,
 'node_442': 12.495422597583396,
 'node_444': 18.579205146495898,
 'node_449': 93.54781369786345,
 'node_451': 210.68556536819398,
 'node_453': 113.36512998046108,
 'node_455': 167.19376463702451,
 'node_457': 47.95597316431765,
 'node_460': 65.10631053259011,
 'node_462': 127.53934219302238,
 'node_463': 133.00296377495187,
 'node_465': 81.99176551767272,
 'node_466': 206.50814146891977,
 'node_468': 59.34443051913073,
 'node_470': 300.9009024594418,
 'node_472': 148.2817590600668,
 'node_474': 126.01287093837541,
 'node_475': 156.49737731130298,
 'node_480': 105.97603957393707,
 'node_495': 59.40127808279344,
 'node_498': 73.22099252240238,
 'node_499': 3.788849545305589,
 'node_502': 140.21267416283763,
 'node_505': 0.59668341670036,
 'node_508': 2.017412896629667,
 'node_510': 68.29760483832548,
 'node_512': 0.536700514890368,
 'node_513': 0.541451494642816,
 'node_515': 225.01740531576144,
 'node_518': 31.830580938690527,
 'node_520': 69.71533805133083,
 'node_523': 18.584082616921723,
 'node_527': 160.37338900939196,
 'node_528': 151.03267859572642,
 'node_529': 160.44664328869638,
 'node_531': 123.44861042913091,
 'node_533': 367.54758690157036,
 'node_535': 334.6596366206346,
 'node_537': 226.4449867198967,
 'node_539': 249.79218763225288,
 'node_541': 89.38114699858721,
 'node_545': 52.0990789879458,
 'node_547': 128.72251669305896,
 'node_549': 12.472457121062023,
 'node_551': 124.21861421113974,
 'node_553': 18.91417076288377,
 'node_555': 177.8792668193109,
 'node_557': 64.62466018641624,
 'node_562': 533.5223773866561,
 'node_565': 188.2044616019531,
 'node_570': 9.351121114956324,
 'node_572': 77.91694360036549,
 'node_575': 300.8880559592868,
 'node_578': 608.7667499550315,
 'node_580': 68.84625194181432,
 'node_582': 166.3938984688483,
 'node_583': 189.78494012312905,
 'node_586': 125.20974016036418,
 'node_599': 180.2347862172422,
 'node_604': 20.578112336327074,
 'node_606': 26.971792867114406,
 'node_607': 31.981181449063307,
 'node_612': 228.6626181898309,
 'node_618': 259.0006269272434,
 'node_636': 91.79152765420496,
 'node_637': 169.37303727990093,
 'node_640': 73.71500565184999,
 'node_641': 265.89094315370113,
 'node_644': 276.01583014581615,
 'node_646': 135.62890116828808,
 'node_647': 431.88021904107444,
 'node_650': 226.68233441906088,
 'node_652': 38.76417269398294,
 'node_654': 104.90700737636213,
 'node_656': 80.05140093309579,
 'node_658': 137.3934140246261,
 'node_660': 16.557342244242477,
 'node_662': 3.085911512796361,
 'node_664': 3.691635610450406,
 'node_665': 4.225549661694485,
 'node_667': 1.598214623999735,
 'node_669': 10.538848825492554,
 'node_670': 159.46864660741238,
 'node_672': 223.06180335935795,
 'node_674': 43.25838101454261,
 'node_676': 11.337213285775402,
 'node_678': 8.960585541192607,
 'node_680': 35.075940162434,
 'node_682': 10.839701177421503,
 'node_683': 85.01500620781874,
 'node_687': 637.5149805920528,
 'node_689': 205.715115132079,
 'node_690': 259.45621492120347,
 'node_697': 105.89035928667582,
 'node_701': 133.04836502052143,
 'node_703': 466.42994665680226,
 'node_705': 246.10449478412136,
 'node_708': 206.54146307181423,
 'node_716': 431.7819630049411,
 'node_721': 204.64363016860705,
 'node_724': 550.0278318496362,
 'node_726': 352.0800286145543,
 'node_741': 117.42794840673538,
 'node_742': 54.43564386760022,
 'node_752': 31.987557667270476,
 'node_754': 46.97507294546944,
 'node_756': 747.4907445829292,
 'node_758': 547.3373868489489,
 'node_760': 902.1805687502259,
 'node_761': 228.7996461373341,
 'node_769': 100.51869559435832,
 'node_773': 485.9933572619516,
 'node_776': 707.3825524206674,
 'node_779': 282.9099813013129,
 'node_790': 222.1965705999656,
 'node_791': 172.02632203790492,
 'node_794': 376.3863105964422,
 'node_797': 573.6883416421941,
 'node_799': 235.9124821911318,
 'node_805': 286.09391270041357,
 'node_810': 589.3994632676822,
 'node_813': 448.91376626690237,
 'node_815': 448.32401153311275,
 'node_819': 235.27886437894432,
 'node_821': 316.67383437061807,
 'node_830': 209.6975274682185,
 'node_831': 56.231331588124455,
 'node_833': 330.24617115965293,
 'node_835': 424.9960595535251,
 'node_836': 80.97191280176396,
 'node_838': 409.4013606537233,
 'node_840': 216.80420581904622,
 'node_846': 465.15569553667063,
 'node_849': 831.8415796500105,
 'node_864': 246.83934936595173,
 'node_866': 88.65289941427271,
 'node_867': 45.113299515404485,
 'node_871': 58.26244037319082,
 'node_875': 71.54915735356391,
 'node_884': 458.28820649357766,
 'node_886': 643.9040421485222,
 'node_889': 567.5044135826089,
 'node_896': 1064.0847759175876,
 'node_897': 284.12266007623896,
 'node_899': 350.84461845511396,
 'node_910': 156.26737843556523,
 'node_912': 150.2664270397981,
 'node_914': 149.0760144671001,
 'node_915': 153.954920335874,
 'node_920': 233.40604487028278,
 'node_927': 500.24246579844515,
 'node_931': 154.9572974869463,
 'node_933': 87.07155477252341,
 'node_934': 116.36504530305031,
 'node_940': 77.15937755671503,
 'node_941': 73.2953259593757,
 'node_946': 183.10171987117562,
 'node_953': 328.70226536101774,
 'node_966': 287.4803185748876,
 'node_972': 101.90172553149213,
 'node_978': 80.62427896966759,
 'node_981': 227.4202338106662,
 'node_983': 208.49637829580206,
 'node_990': 49.390408615675476,
 'node_994': 477.56181785157685,
 'node_996': 89.87684539640301,
 'node_997': 286.7269132155906,
 'node_998': 290.145089375081,
 'node_1001': 50.74530755569995,
 'node_1010': 1522.393774709718,
 'node_1016': 1223.6761829699706,
 'node_1018': 244.33209134703407,
 'node_1023': 322.0033566884558,
 'node_1031': 218.4226764877098,
 'node_1051': 289.35243581870145,
 'node_1073': 261.83454307250116,
 'node_1080': 713.5578391521424,
 'node_1087': 493.32083095507704,
 'node_1088': 190.09899153863444,
 'node_1089': 164.37497629996741,
 'node_1093': 117.97376101364478,
 'node_1097': 221.75171656846516,
 'node_1098': 236.01847102183717,
 'node_1099': 263.96734215625776,
 'node_1101': 158.7629547113017,
 'node_1103': 347.416701213463,
 'node_1105': 175.43037252268246,
 'node_1106': 351.06526189168744,
 'node_1108': 341.64995603485056,
 'node_1109': 229.71647094317453,
 'node_1111': 72.34649762791308,
 'node_1113': 127.29224213435815,
 'node_1115': 127.21357799544688,
 'node_1117': 111.1892556889938,
 'node_1118': 99.66126737857861,
 'node_1120': 331.610271922485,
 'node_1122': 116.87726790601931,
 'node_1124': 234.56937494914445,
 'node_1125': 192.78267343203927,
 'node_1126': 295.9911285927102,
 'node_1128': 103.10441714167337,
 'node_1130': 168.34796308443023,
 'node_1132': 50.28995249305695,
 'node_1134': 402.55285388332237,
 'node_1136': 82.24764782476137,
 'node_1138': 283.1640335958337,
 'node_1140': 212.81140504693138,
 'node_1142': 432.2067946064003,
 'node_1144': 525.603327677215,
 'node_1145': 205.9990768014378,
 'node_1147': 91.83100467341566,
 'node_1153': 13.17533925289144,
 'node_1159': 21.35634961432813,
 'node_1160': 29.4774561692398,
 'node_1163': 81.2961892242129,
 'node_1165': 90.95486337117279,
 'node_1167': 99.10104392995713,
 'node_1172': 103.68816823317411,
 'node_1174': 121.98767567292415,
 'node_1177': 175.6238006076675,
 'node_1179': 113.30728987155469,
 'node_1181': 154.25354732283319,
 'node_1183': 63.10063322263106,
 'node_1187': 89.44904173877856,
 'node_1189': 77.98080677038958,
 'node_1198': 75.43315333562278,
 'node_1199': 377.18778428583056,
 'node_1203': 607.9585163173698,
 'node_1206': 341.73990375892373,
 'node_1213': 339.6324426847614,
 'node_1215': 172.82584133325827,
 'node_1218': 125.53970544837512,
 'node_1219': 22.564987725291154,
 'node_1221': 26.292427241620512,
 'node_1224': 0.092440935451805,
 'node_1225': 0.684242561005035,
 'node_1226': 12.653827780828049,
 'node_1227': 10.315787201594908,
 'node_1230': 15.49341691031329,
 'node_1232': 125.29767509298898,
 'node_1234': 125.75020537014866,
 'node_1236': 110.16641111563425,
 'node_1238': 202.26549925927944,
 'node_1239': 61.22144256346806,
 'node_1241': 47.35819238553101,
 'node_1243': 141.31104498715413,
 'node_1245': 159.36230041252412,
 'node_1247': 112.08399684287428,
 'node_1249': 189.64313474813326,
 'node_1251': 74.83211650477097,
 'node_1253': 186.28854427584318,
 'node_1255': 141.55945240284123,
 'node_1257': 189.1896927310326,
 'node_1259': 57.44354580480346,
 'node_1262': 502.26230669870756,
 'node_1263': 387.4534320545612,
 'node_1264': 376.90260085373876,
 'node_1268': 274.2576937034687,
 'node_1270': 151.2060414474438,
 'node_1272': 450.2381568494349,
 'node_1273': 446.4774048182644,
 'node_1280': 370.60496786144415,
 'node_1290': 714.1584928198428,
 'node_1293': 319.8358130484327,
 'node_1295': 716.5702833784964,
 'node_1296': 398.21990433187494,
 'node_1299': 134.05116972337433,
 'node_1303': 790.029002677815,
 'node_1305': 162.2769057031894,
 'node_1307': 62.023335668709095,
 'node_1309': 490.2669122809224,
 'node_1318': 355.40835572881065,
 'node_1321': 365.935982767581,
 'node_1327': 141.80023495988,
 'node_1332': 434.07959777385327,
 'node_1339': 194.7561904968398,
 'node_1343': 216.2417406343545,
 'node_1346': 268.53987215872235,
 'node_1350': 194.90931392208833,
 'node_1352': 15.53978189669338,
 'node_1353': 380.39531926976593,
 'node_1355': 44.5194915390172,
 'node_1358': 33.3643486621913,
 'node_1360': 45.41639165737715,
 'node_1361': 10.164042348224815,
 'node_1365': 57.957159061742594,
 'node_1368': 194.29192563364205,
 'node_1372': 48.54688449479715,
 'node_1374': 119.53017736571456,
 'node_1376': 101.2626833907399,
 'node_1378': 122.01349894419457,
 'node_1380': 134.8028199348164,
 'node_1382': 144.28169833522543,
 'node_1383': 411.9207040680208,
 'node_1385': 83.62170349202407,
 'node_1387': 68.34045147244433,
 'node_1389': 50.18478513261192,
 'node_1391': 106.41767015597692,
 'node_1393': 71.71604678519085,
 'node_1395': 348.5959998077343,
 'node_1397': 33.76168528210605,
 'node_1399': 101.70507087992621,
 'node_1403': 303.37656027348555,
 'node_1405': 179.73786317532853,
 'node_1407': 173.14593223900266,
 'node_1409': 256.34346333336026,
 'node_1413': 605.868391274237,
 'node_1416': 344.2563306486198,
 'node_1419': 40.62485941100931,
 'node_1426': 165.24679818449596,
 'node_1428': 48.67755127684906,
 'node_1430': 24.449998754009712,
 'node_1436': 32.62034354777482,
 'node_1437': 156.3160972457986,
 'node_1443': 76.05648151596264,
 'node_1445': 132.12898375135066,
 'node_1448': 124.140842187124,
 'node_1455': 199.13475272027128,
 'node_1460': 470.576140120021,
 'node_1463': 640.6185726732822,
 'node_1465': 272.5380341855746,
 'node_1468': 310.2399207926873,
 'node_1471': 200.66186026836743,
 'node_1477': 51.75852125493965,
 'node_1480': 43.58084386107571,
 'node_1484': 35.145727615847726,
 'node_1486': 34.80507012003949,
 'node_1487': 17.249848825909236,
 'node_1489': 21.710218078580056,
 'node_1490': 28.052245342200074,
 'node_1492': 22.69345616284892,
 'node_1496': 43.219796038189585,
 'node_1498': 102.5846720436867,
 'node_1507': 13.12642814602977,
 'node_1510': 8.87456505360455,
 'node_1512': 13.661928855252516,
 'node_1518': 23.302178596436164,
 'node_1520': 22.77161325396479,
 'node_1522': 69.43627935436284,
 'node_1528': 71.66955636857952,
 'node_1534': 236.64372634119644,
 'node_1538': 26.149695144836123,
 'node_1544': 132.63093232057713,
 'node_1546': 47.606323169365794,
 'node_1548': 116.71566867131224,
 'node_1550': 98.61748880619875,
 'node_1553': 74.86839139712337,
 'node_1555': 86.96530546741245,
 'node_1558': 157.6818174026303,
 'node_1563': 93.6274612110293,
 'node_1567': 104.68949784214595,
 'node_1573': 131.08592790474086,
 'node_1577': 64.2087243197617,
 'node_1579': 26.09374351344779,
 'node_1582': 188.11970088721134,
 'node_1591': 106.63422484112075,
 'node_1592': 208.78047775540932,
 'node_1595': 118.69073563994363,
 'node_1603': 336.3282787794026,
 'node_1606': 281.7954875648475,
 'node_1614': 63.622935204772325,
 'node_1616': 245.27143443852765,
 'node_1618': 16.425787709851704,
 'node_1621': 22.866728187118525,
 'node_1623': 182.0150212038565,
 'node_1625': 85.4862405737563,
 'node_1628': 57.31155290918486,
 'node_1630': 141.6310400156739,
 'node_1641': 195.86443613086433,
 'node_1656': 16.48004870565221,
 'node_1658': 224.4178065787916,
 'node_1662': 324.90350835000976,
 'node_1664': 41.22673300852626,
 'node_1669': 93.92607044966368,
 'node_1670': 40.623367904547365,
 'node_1671': 154.5248042554936,
 'node_1675': 245.1001588243866,
 'node_1682': 137.66189985097927,
 'node_1684': 188.2863570482333,
 'node_1688': 207.41398914356998,
 'node_1693': 156.39793784695388,
 'node_1694': 521.5223986094661,
 'node_1696': 244.94896378380344,
 'node_1699': 199.25484544062638,
 'node_1700': 27.46788108659727,
 'node_1702': 21.690516126708523,
 'node_1708': 110.98224773854629,
 'node_1716': 452.55454419138147,
 'node_1718': 284.4951583451508,
 'node_1727': 565.9365217884832,
 'node_1729': 268.66310421805247,
 'node_1734': 65.93525590546625,
 'node_1737': 215.69585556159512,
 'node_1738': 552.0419847475815,
 'node_1740': 69.9098795663061,
 'node_1742': 129.0862792301218,
 'node_1743': 21.983708471783984,
 'node_1752': 153.0887071745907,
 'node_1758': 67.8337591713785,
 'node_1760': 28.089128555172564,
 'node_1762': 64.15453772869391,
 'node_1764': 40.296573738979504,
 'node_1768': 32.497019809881124,
 'node_1775': 421.85261307123443,
 'node_1779': 609.1781011585817,
 'node_1782': 80.13921220410924,
 'node_1783': 200.9861834572324,
 'node_1786': 80.66885807556132,
 'node_1789': 540.6335145807495,
 'node_1798': 225.87602293247593,
 'node_1800': 120.2820807159782,
 'node_1801': 149.9877678417528,
 'node_1805': 350.14762414152716,
 'node_1813': 145.45264682710604,
 'node_1830': 71.39523250409908,
 'node_1831': 67.22792483748219,
 'node_1844': 461.14630747344455,
 'node_1849': 69.45234373228534,
 'node_1860': 53.62399347855699,
 'node_1862': 55.822746560467685,
 'node_1864': 47.86786439006103,
 'node_1870': 13.826510420329946,
 'node_1875': 229.73687468437103,
 'node_1879': 251.81107671242802,
 'node_1888': 365.64257837716826,
 'node_1894': 220.6627241153778,
 'node_1899': 206.92326048077126,
 'node_1902': 238.9169608077152,
 'node_1911': 17.96339028692544,
 'node_1914': 77.78612684389032,
 'node_1915': 83.65168925654632,
 'node_1917': 138.88772636897914,
 'node_1921': 119.36785544878701,
 'node_1925': 66.02341968131816,
 'node_1926': 151.1347296332041,
 'node_1928': 140.25183668440707,
 'node_1930': 61.106380460378816,
 'node_1934': 35.88879422614726,
 'node_1938': 83.2669194828094,
 'node_1941': 60.894464849562056,
 'node_1946': 62.188951487853316,
 'node_1948': 234.95554477350532,
 'node_1953': 198.05572562033464,
 'node_1958': 86.18502520723008,
 'node_1961': 80.18027953276818,
 'node_1963': 49.43372410137212,
 'node_1966': 118.97077750069344,
 'node_1967': 29.400664048662126,
 'node_1972': 129.33033953033672,
 'node_1979': 311.4457898990905,
 'node_1986': 215.88477565280488,
 'node_1989': 342.542338061947,
 'node_1991': 496.0447418188273,
 'node_1995': 254.7322477171552,
 'node_2000': 414.4119836870569,
 'node_2002': 383.85709863138777,
 'node_2004': 574.4669384720003,
 'node_2006': 98.82029262730508,
 'node_2012': 38.82755928741878,
 'node_2014': 80.44718394367764,
 'node_2016': 98.00292505750285,
 'node_2018': 991.6124239221765,
 'node_2022': 182.24166553282976,
 'node_2027': 159.9088299453706,
 'node_2030': 112.73346603581079,
 'node_2032': 234.08406918250355,
 'node_2033': 348.6386098640466,
 'node_2036': 540.814608085054,
 'node_2039': 254.2594453533827,
 'node_2044': 230.5719527904531,
 'node_2046': 8.488292993273028,

In [11]:
population_dataframe = gpd.read_file('../data/population-russell/population.gpkg')

In [12]:
population_dataframe

,ED_CLASS,ED_ID,AREA,PERIMETER,PARISH,CONST_NAME,ED,population,geometry
0,URBAN,805001.0,5.143341e+04,1467.073643,ST.JAMES,CENTRAL,C 1,369.0,"MULTIPOLYGON (((655402.607 703302.232, 655405...."
1,URBAN,805010.0,7.038129e+04,1372.112659,ST.JAMES,CENTRAL,C 10,942.0,"MULTIPOLYGON (((657099.789 703165.659, 657120...."
2,URBAN,805011.0,3.384452e+04,853.438071,ST.JAMES,CENTRAL,C 11,696.0,"MULTIPOLYGON (((657356.520 702842.406, 657245...."
3,URBAN,805012.0,6.197154e+04,1329.276904,ST.JAMES,CENTRAL,C 12,651.0,"MULTIPOLYGON (((657595.582 702863.194, 657594...."
4,URBAN,805013.0,1.948088e+05,1869.497643,ST.JAMES,CENTRAL,C 13,624.0,"MULTIPOLYGON (((658058.365 703130.287, 658094...."
...,...,...,...,...,...,...,...,...,...
5771,RURAL,501081.0,9.176006e+05,7759.890673,ST. MARY,SOUTH EAST,SE 81,458.0,"MULTIPOLYGON (((767463.380 669418.968, 767496...."
5772,RURAL,501094.0,4.122719e+06,10992.812654,ST. MARY,SOUTH EAST,SE 94,871.0,"MULTIPOLYGON (((764339.677 670084.973, 764356...."
5773,RURAL,501080.0,1.421954e+06,9950.536198,ST. MARY,SOUTH EAST,SE 80,939.0,"MULTIPOLYGON (((767901.801 669680.689, 768156...."
5774,RURAL,501057.0,7.599783e+05,5588.089562,ST. MARY,SOUTH EAST,SE 57,135.0,"MULTIPOLYGON (((764148.478 673352.650, 764275...."
5775,RURAL,503071.0,6.189344e+05,4634.975815,ST.MARY,WEST,W 71,406.0,"MULTIPOLYGON (((756402.058 690082.207, 756433...."